config/routes.rb
Rails.application.routes.draw do
  root to: 'site#index'

  namespace :api do
    namespace :v1 do
      resources :articles, only: [:index, :create, :destroy, :update]
    end
  end

  resources :articles do
  	resources :comments
  end
  
  # get "/search"

end

app/models/article.rb
class Article < ActiveRecord::Base
	enum level: [:bad, :halfbad, :fantastic]

	validates :title, presence: true
	validates :body, presence: true

	is_impressionable
	has_many :comments # , as: :commentable # polymorphic: true

	# acts_as_commentable

	# def self.search(search)
	# 	if search 
	# 		find(:all, :conditions => ['name LIKE ?', "%#{params[:search]}%"])
 #    	else
 #    		find(:all)
 #    	end
 #    end

	# searchable do
	# 	text :title, :body		
	# end

	# acts_as_taggable
	# acts_as_taggable_on :body

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	# belongs_to :commentable, polymorphic: true
	belongs_to :article, :foreign_key => 'article_id'
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < Api::V1::BaseController
  def index
    respond_with Article.all
  end

  def create
    respond_with :api, :v1, Article.create(article_params)
  end

  def destroy
    respond_with Article.destroy(params[:id])
  end

  def update
    article = Article.find(params["id"])
    article.update_attributes(article_params)
    respond_with article, json: article
  end

 private

  def article_params
    params.require(:article).permit(:id, :title, :body, :level)
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  respond_to :json
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  impressionist :actions=>[:show, :index]

  def index
    # @articles =  Article.search(params[:search])

    if params[:search]
      @articles = Article.where(
       "lower(title) LIKE lower(?)",
       "%#{Regexp.escape(params[:search])}%"
       )
      @articles.class == Array
      @articles = Kaminari.paginate_array(@articles).page(params[:page]).per(5) 
    else
      @articles = Article.all.order("created_at DESC").page(params[:page]).per(5)
    end

    # @search = Article.search do
    #   fulltext params[:search]
    # end
    # @articles = @search.results

    # @articles = Article.all
    # @markdown = Redcarpet::Markdown.new(RedCarpet::Render::HTML)
  end

  def show
    impressionist(@article)
    @comments = @article.comments.all
  end

  # def commenting
  #   impressionist(@article)
  # end

  # def search
  #   @articles = Article.all
  #   if params[:search]
  #     @articles = Article.find(:all, :conditions => ['name LIKE?', "%#{params[:search]}%"])
  #   else
  #     @articles = Article.find(:all)
  #   end    
  #   erb :"result"
  # end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body, :tag_list)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_article

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = @article.id

    if @comment.save
      redirect_to article_path(@article)
    else 
      render 'new'
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  	def comment_params
  	  params.require(:comment).permit(:comment_body)
    end

	 def find_article
  	  @article = Article.find(params[:article_id])
    end

  end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  	@articles = Article.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)
#		Redcarpet.new(text).to_html.html_safe
    options = {
      filter_html:     true,
      hard_wrap:       true, 
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true, 
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

		renderer = Redcarpet::Render::HTML.new(options)
	    markdown = Redcarpet::Markdown.new(renderer, extensions)

	    markdown.render(text).html_safe
	end
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<br>
<br>

app/views/articles/edit.html.erb
<div class="container">
	<h1>Editing Article</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @article, class: 'btn btn-info' %> |
	<%= link_to 'Back', articles_path, class: 'btn btn-info' %>
</div>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="pull-left control-group">
    <%= link_to 'New Article', new_article_path, class: 'btn btn-info'%>
  </div>
  <div class="pull-right control-group">
    <%= paginate @articles %>
  </div>
</div>

<div class="col-sm-12">
  <% if (@articles.empty?) %>
    <br>
    <h2>Sorry, no articles found.</h2>
    <% else %>
  <% end %>
    
    <% @articles.each do |article| %>

    <div class="col-sm-6">
      <div class="panel-group">
        <div class="panel panel-default">
          <div class="container">
            <br>
            <%= markdown(article.title) %>
          </div>
          <div class="panel-body">
            <%= markdown(article.body) %>
          </div>

          <div class="panel-footer">
            Number of views: <%= article.impressionist_count %>
            <div class="pull-right control-group">
              <%= link_to "View", article_path(article), class: 'btn btn-xs btn-info' %>
              <%= link_to "Edit", edit_article_path(article), class: 'btn btn-xs btn-info' %>
              <%= link_to 'Delete', article, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-xs btn-warning' %>
            </div>
          </div>
        </div>
      </div> 
    </div>
  <% end %>
</div>
  

app/views/articles/new.html.erb
<div class="container">
	<h1>New Article</h1>
	<%= render 'form' %>
</div>

<%= link_to 'Back', articles_path, class: 'btn btn-info' %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= markdown(@article.title) %>
</p>

<p>
  <strong>Body:</strong>
  <%= markdown(@article.body) %>
</p>
Number of views: <%= @article.impressionist_count %>
<br>

<h3>Comments</h3>
<%= render @article.comments %>
<%= button_to "Add a Comment", new_article_comment_path(@article), :method => :get %> 

<br>
<%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-info' %> |
<%= link_to 'Back', articles_path, class: 'btn btn-info' %>

app/views/comments/_comment.html.erb
<div class="panel-body panel-height">
<%= comment.comment_body %>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for ([@article, @article.comments.build]) do |f| %>
  <%= f.input :comment_body %>
  <%= f.button :submit %>
<% end %>

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light bg-faded">
  <a class="navbar-brand" href="/">Juan's Blog</a>
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="/">React.JS Version <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/articles">Normal Version</a>
    </li>
  </ul>
        <%= form_tag articles_path, :method => 'get' do %>
        <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil %>
        </p>
      <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render 'layouts/header' %>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/site/index.html.erb
<%= react_component 'Main' %>
<br>
<hr>
<h3>The <b>non-React</b> version is <%= link_to 'here', articles_url %>. It has the Markdown functionality</h3>